redlib-org/redlib

static/style.css
I found that my previous fix for this had a problem where the footer would end up on the wrong spot in very short posts that had no comments, sorry about that!
This is a much simpler fix to the problem that also avoids running into that issue.
After another look I realized that the problem revolves around what classes the body has. Only the fixed_navbar class had `position: relative;` and therefore when the body lost that from turning "Keep navbar fixed" off, the footer was no longer relative to the body. Hence why it would show up at the bottom of the initial viewport and be fixed there.
This fix just restores the old CSS file and gives the card class the same properties as the fixed_navbar class besides it's top padding in order to make sure both are in line with each other and combat …
=> Less buggy solution to solving the floating footer problem

src/client.rs
A 401 code is still an `Ok(<...>)` response, so the error handling was in the wrong place.
Hopefully the conditional logic (`json["reason"] == "Unauthorized"`) is correct;
The information reported to the browser _should_ be improved.
It's obvious that Libreddit wasn't designed with error-handling in mind.
Linked issue: #22
=> Handle errors from reddit

src/config.rs
[Unddit](https://www.unddit.com) shut down for a while, and have been ineffective after [PushShift](https://pushshift.io/) drastically changed. [PullPush](https://pullpush.io/) is a spiritual successor to PushShift and [also provide a service similar to Unddit](https://undelete.pullpush.io/). I went ahead and replaced the string to a working link so that removed post links aren't broken by default.
=> Replace www.unddit.com with undelete.pullpush.io

Cargo.lock, Cargo.toml, src/client.rs
- Cargo update
- Update major non-breaking changes
- Add deprecation feature-flags to hyper v0.14
- Semi-upgrade hyper-rustls
=> Update dependencies (Hyper v1.x)

compose.yaml, docker-compose.yml
Docker compose complains with "mapping key "security_opt" already defined"
=> Update docker-compose.yml to remove duplicate 'security_opt'

docker-compose.dev.yml, docker-compose.yml, static/playHLSVideo.js, static/style.css
May close #41 
I have tried adding the quality change feature, it works but with a delay as it waits for the current segment to finish playing. Please check it out and suggest changes.
I also found some repositories related to this. https://github.com/sahilkashyap64/hls and https://github.com/kmoskwiak/videojs-resolution-switcher but they require some more dependencies.
=> Added video quality feature

.env.example, README.md, compose.yaml
This PR mostly expands on Docker-related documentation for Redlib. Configuration using an [`.env` file](https://docs.docker.com/compose/environment-variables/set-environment-variables/) for Docker deployments is now covered.
Some formatting changes have also been made in the README (headings and admonitions).
An error in `compose.yaml` that causes Docker Compose deployments to break has also been fixed (see last bullet point).
As a quick summary of changes:
- Modified Docker CLI commands in `README.md` as well as values in `compose.yaml` to explicitly specify the `latest` tag for the Redlib image.
- Added a new section covering Docker Compose deployments.
- Added documentation covering the use of a `.env` file to configure Redlib using environment variables for Docker deployments.
- Added …
=> Expand Docker documentation

static/playHLSVideo.js
Video playback is broken for me on Android Firefox/123.0.
Based on the documentation here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType
According to the page above, the canPlayType call has 3 possible return values: "", maybe, probably. Maybe means "There is not enough information to determine whether the media can play" so simply checking if the string has a value seems to be incorrect in this case. This change updates the check to test if the browser returns at least "probably".
=> Make HLS support checking more robust

static/style.css, templates/base.html
Fixes https://github.com/redlib-org/redlib/issues/79
The site didn't account for the navbar being there when it jumps somewhere. Adding the `scroll-padding-top` attribute fixes this by telling the browser to scroll further.
I had to add the `fixed_navbar` class to `html` as otherwise you'd have to add it to each element you're jumping too, which would be far more complicated and would require actual code.
Every other reference to the `fixed_navbar` class in `style.css` is targeting the class for a specific type of element, so it doesn't have any extra effects but might be something to keep in mind if any more work is done with the class.
=> Fix anchor tags scrolling to the wrong place when fixed navbar is enabled

src/utils.rs
This fixes https://github.com/redlib-org/redlib/issues/48
The original rewrite_urls function would only run format_url once and then replace all Reddit preview links with that result.
The updated code replaces each match at a time until no more are left, running format_url on each match instead so their all replaced with their respective formatted URL.
One side effect of this is that the text for the link no longer shows `https://preview.redd.it/` and instead shows `/preview/pre/`. Whether this is a bug or a feature is up to you, but personally I like it showing `/preview/pre/` better since I know I'm staying on Redlib.
I've *basically* never worked with Rust and this took me many tries to get a working solution so hopefully it's up to par.
=> Fix multiple Reddit preview links becoming the same

src/utils.rs, static/style.css
Of course I happened to discover some bugs _after_ https://github.com/redlib-org/redlib/pull/85 was merged.
1. The regex matches would sometimes match more than expected depending on how the post was typed out. This would cause parts of the post to get overwritten or merged with the embed. I made the wildcard matches lazy to prevent this.
2. Gifs would duplicate because the replace parameter wasn't specific enough and would match already existing img blocks. Now it has to match the entirety of `<a href="PREVIEW_LINK">TEXT</a>` which is then replaced by `<a href ="PREVIEW_LINK"><img src="PREVIEW_LINK"></a>`
3. Embedded images in comments wouldn't keep their aspect ratio when the screen got small because I forgot to specify the height attribute as auto. All I did was add that in the CSS.
On …
=> Handle preview embedding better

README.md
Closes #111
The `PORT` environment variable was missing in the docs, this PR adds it. I also aligned the tables.
=> Add `PORT` env to docs

static/style.css
Just happened to notice this funny little bug.
The media attributes for controlling which text would appear in the footer both did nothing at 480px so I just made it so the one for the mobile links would display at 480px and left the desktop links as is.
=> Stop post footer text from disappearing when screen is exactly 480px wide

src/config.rs
The documentation/examples here don't match the variable that gets parsed, leading to the variable not taking effect if the documentation/examples are followed.
I've updated the expected variable name in code, as "HIDE_HLS" is only referenced a single time, while every other reference is to "HIDE_HLS_NOTIFICATION", but this *is* a breaking change; anyone who had `REDLIB_DEFAULT_HIDE_HLS=on` will see their setting stop working.
If you'd prefer, I can amend the PR/fix to instead update the documentation to match the code, which would make the fix non-breaking, at the expense of consistency of variable names.
=> Update hide HLS env var to match documentation

src/client.rs
=> fix(oauth): Make Android user-agent patching unconditional

.github/workflows/build-artifacts.yaml
Only build artifacts on published release.
As of now the artifacts are never created as the branch must be "main" on line 9 but must not be "main" on line 63.
fixes #71
fixes #74
fixes #122  
fixes #132
=> Create build-artifacts on release

README.md, compose.yaml
Just a couple more documentation fixes; since the recent fixes to the build, the `latest` tag now includes both ARM and ARM64 images. (And the `latest-arm` and `latest-armv7` tags point to some images from 3 months ago.)
=> Remove obsolete references to latest-arm and latest-armv7 images

src/config.rs
This change fixes the REDLIB_DEFAULT_HIDE_SIDEBAR_AND_SUMMARY environment variable being ignored.
On a fresh private session with no prior cookies stored, when `REDLIB_DEFAULT_HIDE_SIDEBAR_AND_SUMMARY=on`, pre-change, the `Hide the summary and sidebar` setting is be unset. Post-change, it's set when the env var is set to `on`.
=> Properly apply REDLIB_DEFAULT_HIDE_SIDEBAR_AND_SUMMARY

Dockerfile
Fix typo causing wget to return a warning:
```
wget: option '--q' is ambiguous; possibilities: '--quiet' '--quota'
```
=> fix: healthcheck in Dockerfile

.envrc, .gitignore, flake.lock, flake.nix
This pr adds a simple nix flake to aid development/building for nix users without having to manually configure the rust toolchain. 
I set this up to target musl, but actually it probably isn't necessary at all, since with nix, the docker image can be built directly. If you want, I could test/change it to the default target. It is also hardcoded to x86_64 at the moment, but it's probably fine(?) since I'm not trying to replace the existing workflows, but rather just provide an entrypoint for nix users.
The binary can be built with `nix build` and the docker image with `nix build .#docker`, after which you can load it with `docker load < result`. The docker image created here is not exactly the same as the Dockerfile in the repo (I don't create a redlib user) but it is compatible with the …
=> add nix flake

static/style.css
This makes Safari render the bold weights correctly which otherwise looks wrong.
See how the subreddit name (i.e _r/AskReddit_) is rendered between the images below.
| Before | After |
| -------|------|
| ![libreddit_cssfw_before](https://github.com/redlib-org/redlib/assets/2759499/d1ee9b30-971c-44b4-a5e2-17196bc5ec5b) | ![libreddit_cssfw_after](https://github.com/redlib-org/redlib/assets/2759499/0e287603-53f6-4efb-812a-968ea99f6f44) |
=> Add font-weight range in @font-face rule

.env.example, .gitignore, app.json, src/config.rs, src/instance_info.rs
=> Default filters

src/main.rs
As I stated in #108, with docker added support to IPv6, the healthcheck fails since the server only listens on IPv4 by default. The best fix is to make the server listen on both IPv6 and IPv4 by default.
Otherwise, this can be fixed by replacing `localhost` with `127.0.0.1` in the healthchecks
=> Make server listen on both IPv6 and IPv4 by default to fix docker healthcheck

src/client.rs, src/oauth.rs
reset rate limit as soon as we encounter a low rate limit, rather than once we finish retrieving a new token
if this doesn't work, my next choice is a single thread owning write access to `OAUTH_CLIENT` that can receive a reset signal from anywhere, and keeps track of the rate limits to allow both the expiry event and the rate limit event to reset it, without causing concurrent token retrievals
=> fix(oauth): reset rate limit earlier in refresh cycle

src/client.rs, src/oauth.rs
throw more atomics at it why don't you?
=> fix(oauth): even more atomics to avoid simultaneous token rollover

src/utils.rs, static/style.css, templates/utils.html
Resolves #66
- For video's it downloads the mp4 fallback file, not the HLS video
- I've created a 'user friendly' filename for the download using a fixed prefix (not-configurable) and the last path segment of the permalink (this should be the post title). This is because the mp4 fallback filename itself is basically just the resolution (fe 480.mp4).
- Cleaned up the desktop/mobile logic + styles
FWIW: I first looked into fixing that you cannot download the video by long pressing on the HLS player. The reason for this issue is that in `playHLSVideo.js` the player src is set to `newVideo.src = "about:blank";`
If we would change the `newVideo.src` to the mp4 url, then you could long press the player and download the video _before_ you click play. But the issue is that when you click play, …
=> feat: add download button on image/gif/video posts

templates/utils.html
Posts with type gif did not play sound when being displayed in the list overview. This was caused by a difference in the utlis `post` and `post_in_list` macros, causing gif posts not being played thru hls.
The mp4 fallback_url doesn't have sound embedded btw, this is ofc also the case when downloading the mp4 file. So if hls is disabled then the gif post still doesn't have sound.
=> fix: also use hls if possible for gifs in post_in_list macro

static/style.css, templates/user.html
Fixes #180
Before:
After:
The UI remains unchanged when screen width is greater than 480px
=> Improve post information widget of user comments for devices under 480px width 

static/style.css, templates/search.html
Closes #143 
This PR makes the search bar responsive and in turn usable on mobile devices. 
On screens whose width is lower than 480px the search bar's design will become:
=> Make search bar responsive on mobile devices

README.md
The documentation was missing the `HIDE_SIDEBAR_AND_SUMMARY` environment variable.
=> fix(docs): Add env `HIDE_SIDEBAR_AND_SUMMARY`

static/style.css
This pull request just readds `#searchbox > * { font-size: 15px; }` in order to set the font size of the searchbox text.
It looks like this bug was introduced in https://github.com/redlib-org/redlib/commit/410872d988c029373e614ad56c20615a75565740 when `#search_sort > *, #searchbox > * { font-size: 15px; }` was removed.
When that happened it made the subreddit name inherit the 20px font size of the navbar instead of having 15px font size like before, and I'm not sure where the placeholder "search" text (and whatever was inputted there) was inheriting it's font size from since it wasn't the 20px, but this corrects it to be 15px again as well.
Current latest commit (https://github.com/redlib-org/redlib/commit/4205959adeed9ed581b41c27f0cdb15609950316 at time of posting):
This pull request:
=> Fix font sizes in search bar being incorrect

static/style.css
This just removes a problematic option added in https://github.com/redlib-org/redlib/commit/410872d988c029373e614ad56c20615a75565740
Current commit:
This pull request (you can scroll side to side on the sort options):
=> Fix sort options overflow on small screens

Cargo.toml
Update the license tag to `AGPL-3.0-only` as `AGPL-3.0` is deprecated and ambiguous.
=> Update license tag

templates/comment.html
This makes it so you jump directly to the comment when you load the page. Super useful for those insanely long posts with a bunch of pictures.
Every comment already has a specific ID so I just set that as the anchor on the link.
=> Add anchor to comment link

static/style.css, templates/base.html, templates/settings.html, templates/utils.html
In no particular order this fixes:
- Subreddit info overflowing on very small screens
- Posts having an odd right side gap shortly before swapping to the mobile layout
- The searchbox having a small gap on the right at and below 800px
- The sort submit button on user profile being too short at and below 480px (new bug introduced in 410872d988c029373e614ad56c20615a75565740)
- The search bar becoming scrollable slightly before swapping to the new mobile layout (new bug introduced in 410872d988c029373e614ad56c20615a75565740)
- Fixed and unfixed navbar options having differently spaces gaps between the content and the navbar
- Up/downvote numbers overflowing their container when in the extra small mobile layout
-  redlib-org#172
- Search box being slightly skewed offcenter
- Post flair not …
=> Fix a whole bunch of styling bugs

static/style.css
- Ensures that when you hover over a video spoiler, the post body is also unblurred & vice versa
- Set min size of video player for when the poster image doesn't load due to a 403 or 404 from upstream
=> fix: spoiler hover and video size

src/client.rs
=> fix(oauth): catch network policy violation and rate limit

src/oauth.rs
=> fix(client): add a timeout and retry logic to oauth daemon

src/client.rs
=> fix(client): catch json suspended user error

Cargo.lock, Cargo.toml, src/main.rs, src/post.rs, src/utils.rs
Fixes #206 
Really just the title.
The (most) bit is because some emotes simply don't show up in the "media_metadata" section of Reddit's JSON and I simply cannot find another spot to get the actual link to this emotes.
Not sure what the difference is between working and nonworking emote that causes some to be there while others aren't.
Before:
After:
=> Fix #206 and make (most) emotes embed in comments

static/style.css, templates/user.html
https://github.com/redlib-org/redlib/pull/212 didn't work from within a user's page, this fixes that.
Also the last `<p>` item inside of the post and comment bodies didn't get the proper gap above it, leading to the last two lines of text getting squashed together. This fixes that.
This was originally intended to have more fixes in it but as I started working on them I realized a lot of the stuff I noted down didn't need fixing or wasn't feasible to fix without JS.
Was also originally supposed to go along with https://github.com/redlib-org/redlib/pull/218 but I thought that pull request was gonna be larger so it became it's own branch.
=> Make jump to comment work from user's page and make last <p> in the post and comment bodies get the margin above it like the others

Cargo.lock, Cargo.toml
There were few changes between 6.0.0 and 7.0.0, and it looks like https://github.com/dropbox/rust-brotli/commit/41cadaabb6c650ae518b30509a5fbe43ca8cfab9 was the only breaking one. I confirmed that `cargo test -- --exact --skip client::test_share_link_strip_json --skip utils::test_fetching_nsfw_subreddit --skip client::test_obfuscated_share_link` still passes. (The three skipped tests already fail on `main`.)
=> chore(deps): Update brotli from 6.0 to 7.0

README.md
Adds all remaining themes to the available options list for the `REDLIB_DEFAULT_THEME` environment variable.
This is a followup from #281.
=> Add additional themes to README

Cargo.lock, src/client.rs, src/post.rs, src/scraper/main.rs, src/search.rs, src/server.rs, src/settings.rs, src/subreddit.rs, src/user.rs, src/utils.rs
CI has been failing for awhile now, and this PR aims to get things to pass. I'm not completely sure if my fix to the test is correct, and I'm sure there's a way to properly fix the clippy::cmp_owned errors. In addition, cargo-audit showed that a few dependencies were yanked, so I went ahead and bumped them.
=> Fix parts of CI

Dockerfile
kaniko in k8s would not expand the `TARGET` arg without double quotes around it.
=> Use quotes for kaniko to expand ARG in Dockerfile

README.md, redlib.container
I'm working with Quadlet files, which simplify the deployment of systemd units for Podman containers. They are similar to docker-compose, but for podman and systemd.
For those who have not used Quadlets, this file should be placed at `.config/containers/systemd/redlib.container` and would use podman and systemd to automatically start and run the container on boot for users that have `enable-linger` turned on
=> Add Quadlet Container File

scripts/update_oauth_resources.sh, src/client.rs, src/oauth.rs, src/oauth_resources.rs
- For global variables which don't need to be mutable, prefer `const` to `static`.
=> refactor: replace static with const for global constants

src/server.rs
This PR changes the Redlib router to call the GET handler on HEAD requests, discard the body (skipping compression) and returning only headers.
Resolves #292
=> Support HEAD requests (resolves #292)

Cargo.lock, Cargo.toml, src/utils.rs
The json api at https://www.reddit.com/r/emulation/hot.json returns selftext_html as a escaped html string.
This was passed straight to the rss output, causing rendering issues.
Instead, unescape the html, which will be embedded it in rss as  `<content:encoded><![CDATA[ selftext_html ]]></content:encoded>`
Question: I am not sure it is necessary to add yet another dependency (htmlescape), maybe the functionality exists in some other already imported crate?
=> unescape selftext_html from json api, fixes #354

Dockerfile.alpine, Dockerfile.ubuntu
this PR adds 2 new dockerfiles that allow users & developers to build containers from source in reference to [previous discussion](https://github.com/redlib-org/redlib/pull/59#issuecomment-2356608473), restoring functionality that was lost in https://github.com/redlib-org/redlib/pull/59. one issue i see people facing is that doing a docker build against a specific branch or commit unexpectedly ignores that and uses the latest release.
the original dockerfiles were:
* [Dockerfile](https://github.com/redlib-org/redlib/blob/22910956dbce2a4c8abae0016ecda251b268332c/Dockerfile)
* [Dockerfile.arm](https://github.com/redlib-org/redlib/blob/22910956dbce2a4c8abae0016ecda251b268332c/Dockerfile.arm)
* [Dockerfile.armv7](https://github.com/redlib-org/redlib/blob/22910956dbce2a4c8abae0016ecda251b268332 …
=> [build] add new dockerfiles for building from source

flake.lock, flake.nix
The current Rust version used in redlib is too old to compile recent changes. This updates all Nix dependencies.
=> build(nix): update deps

src/utils.rs
I found that bullet lists (unordered lists) were not rendered with redlib. This patch fixes that.
Example: https://www.reddit.com/r/Monitors/comments/69gu2z/lg_24mp59gp_settingscalibration_guide/
Before this change, all bullet items are squished together, making it hard to read:
After the change, bullet list is properly rendered with `<ul>` and `<li>` tags:
Pls kindly review :)
=> feat: render bullet lists

src/utils.rs
Fixes https://github.com/redlib-org/redlib/issues/195
Before:
After:
If you want to test it yourself:
Broken crossposted gallery: `/r/homelab/comments/1fsrxj9/designed_my_own_storage_chassis_with_up_to_56_bays/`
Original post: `/r/DataHoarder/comments/1fsrvko/designed_my_own_storage_chassis_with_up_to_56_bays/`
=> Fix crossposted galleries not working

.devcontainer/devcontainer.json
The existing config for Dev Containers doesn't work. Currently, is fails to build the project because the image uses an outdated version of rust, that is not supported by one or more dependencies.
This PR updates the used image to the most recent one and resolves the problem.
=> fix: update devcontainer image

src/utils.rs
Was caused by rewrite_urls() not replacing the original `<p>` and `</p>` surrounding the image link.
Before:
After:
=> Fix embedded images sometimes having gaps around them

src/server.rs
When running on Linux, listen for SIGTERM in addition to CTRL+C.
I am not incredibly competent with Rust and Linux is my daily driver, so please double-check my changes. Regardless, this should behave relatively the same on Linux and Windows, past the "Failed to install CTRL+C signal handler" error not appearing on Linux if redlib fails to install that signal handler.
This also fixes #205.
=> fix: gracefully shutdown on CTRL+C and SIGTERM on Linux

src/utils.rs
- Avoid redundant String conversions
- Replace if with match to enhance code readability
=> refactor(utils): avoid redundant String conversions & use match

static/check_update.js
Since there's an onion instance in the list without a `url` value, occasionally the redirect gives `undefined` as instance domain. This avoids it for clearnet users.
For users on an onion domain this will return only onion instances, though this might not be the most appropriate choice right now given that there is only one onion instance...
=> fix: avoid redirecting to undefined instance

src/client.rs, src/config.rs, src/duplicates.rs, src/instance_info.rs, src/search.rs, src/settings.rs, src/utils.rs
This makes the documentation generated with `cargo doc` quite a bit more readable. Also fix a few typos while we're at it.
=> Convert lots of comments to doc comments

Cargo.lock, Cargo.toml, src/client.rs, src/config.rs, src/instance_info.rs, src/main.rs, src/oauth.rs, src/post.rs, src/search.rs, src/subreddit.rs, src/utils.rs
This has been in std since Rust 1.80. We currently need Rust 1.81 to build (#478), so there's no reason not to use it and remove our direct dependency on once_cell.
=> Use `std::sync::LazyLock` instead of `once_cell` version
