- src/client.rs
- src/subreddit.rs
> Fix /r/popular localization - set geo filter to global

- static/style.css
> Fix floating footer with "Keep navbar fixed" off

- src/client.rs
- Refresh token conditionally on 401 code
Linked Issue: #22
> Refresh OAuth on 401 only

- .env.example
- README.md
Matches the change in 3592728.
Just fixes a couple of documentation/examples to have their defaults match the current configured defaults.
> Update PUSHSHIFT_FRONTEND examples to undelete.pullpush.io

- README.md
- static/themes/icebergDark.css
Add a theme based on [iceberg](https://github.com/cocopon/iceberg.vim) by cocopon
> feat: add icebergDark theme

- src/subreddit.rs
Implements: https://github.com/redlib-org/redlib/issues/101
> added geo_filter query param to /r/popular endpoint

- src/subreddit.rs
https://github.com/redlib-org/redlib/issues/151#issuecomment-2188052256
fixes #117 - reason why this took so long is because it was hard to tell from issue that it only happens in multi reddits. which may be hard to reason about since it could be the cookie-default
> fix(subreddit): handle plus-encoding errors

- src/client.rs
- src/oauth.rs
Fixes https://github.com/redlib-org/redlib/issues/155
Tested locally and ensured that the key rolled over when the rate limit is close.
> feat(oauth): roll over oauth key on rate limit

- Cargo.lock
- Cargo.toml
- src/client.rs
- src/oauth.rs
I see now an async RwLock might not have been ideal. This is hopefully a better solution. cc @freedit-dev
> fix(oauth): arc_swap

- src/subreddit.rs
> fix(subreddit): handle plus-encoding errors even better

- src/utils.rs
> fix(posts): manually sort by created date

- src/utils.rs
> fix(posts): manually sort by flags

- src/subreddit.rs
- src/utils.rs
> fix(posts): fix sort call on new

- static/style.css
- templates/utils.html
chore: simplify blur classes
Just blurring the image/video of a post really isn't enough with spoilers sometimes ;)
> feat: also blur text in post body for spoilers

- src/client.rs
- src/subreddit.rs
Live from the [Boston Rust hackathon](https://www.meetup.com/bostonrust/events/301934387/)...
Fixes #109
> fix(client): handle new gated and quarantined error types

- src/utils.rs
- templates/base.html
> Insert noindex meta for ROBOTS_DISABLE_INDEXING (#199)

- templates/utils.html
> feat(post): add archive.is link for link posts

- .github/workflows/main-docker.yml
Updated digest name on download (as per 1187084). Based on https://github.com/redlib-org/redlib/issues/229#issuecomment-2354001787
> Update main-docker.yml (digests)

- .github/workflows/main-docker.yml
Trying another fix based on the template provided here https://github.com/actions/download-artifact for downloading multiple (filtered) Artifacts to the same directory
> Attempting to fix main-docker.yml for downloading digests 

- static/style.css
- templates/utils.html
Makes it so the poll results appear inside of the post instead of just outside of it.
> Make poll results appear inside of a post

- src/oauth.rs
> chore(client): update new oauth path

- src/search.rs
> fix(search): handle multi-sub search

- src/post.rs
> fix(search): handle queries' urlencoding

- src/instance_info.rs
- src/main.rs
- static/check_update.js
- templates/error.html
> feat: display whether or not the instance is up to date on error

- README.md
- src/main.rs
> feat: add environment variables and dedicated flags for ipv4/6 only

- README.md
- src/settings.rs
- src/subreddit.rs
- src/utils.rs
- templates/info.html
- templates/settings.html
- templates/utils.html
> feat: hide default feeds option

- static/themes/midnightPurple.css
a pure black theme with midnight purple accent
> style(theme): add MidnightPurple

- templates/post.html
> feat: display contexted title if link is single-thread

- static/style.css
Issue #391 highlighted an issue with the margins of the 'Copy' and 'Import' buttons in the Settings page. This PR addresses that style issue.
> fix: Copy and Import button layouts

- static/check_update.js
- templates/error.html
Hoping this could help out a little.
> Update error to refer to latest rate limit issue
